# Generated by Django 5.2.8 on 2025-11-21 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_zona', models.CharField(choices=[('jardin', 'Jardín'), ('huerto', 'Huerto'), ('cesped', 'Césped'), ('cultivo', 'Cultivo'), ('ornamental', 'Ornamental')], default='jardin', max_length=20)),
                ('area_m2', models.DecimalField(decimal_places=2, help_text='Área de la zona en metros cuadrados', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('capacidad_agua_litros', models.DecimalField(decimal_places=2, help_text='Capacidad de agua en litros', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'Mantenimiento')], default='activa', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona de Riego',
                'verbose_name_plural': 'Zonas de Riego',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_sensor', models.CharField(choices=[('humedad', 'Humedad de Suelo'), ('temperatura', 'Temperatura'), ('lluvia', 'Lluvia'), ('presion', 'Presión de Agua'), ('caudal', 'Caudal')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'Mantenimiento'), ('averiado', 'Averiado')], default='operativo', max_length=20)),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Última lectura del sensor', max_digits=10, null=True)),
                ('unidad_medida', models.CharField(default='%', max_length=20)),
                ('umbral_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo de alerta', max_digits=10, null=True)),
                ('umbral_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo de alerta', max_digits=10, null=True)),
                ('fecha_instalacion', models.DateField()),
                ('ultima_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='zonas_riego.zona')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['-fecha_instalacion'],
            },
        ),
    ]
