# Generated by Django 5.2.8 on 2025-11-21 14:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas_riego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del riego')),
                ('duracion_minutos', models.IntegerField(help_text='Duración del riego en minutos (máx. 24 horas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('personalizada', 'Personalizada')], default='diaria', max_length=20)),
                ('dias_semana', models.JSONField(blank=True, default=list, help_text='Lista de días de la semana para riego semanal')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la programación')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la programación (opcional)', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('caudal_litros_minuto', models.DecimalField(decimal_places=2, help_text='Caudal de agua en litros por minuto', max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('prioridad', models.IntegerField(default=1, help_text='Prioridad de la programación (1=baja, 10=alta)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='zonas_riego.zona')),
            ],
            options={
                'verbose_name': 'Programación de Riego',
                'verbose_name_plural': 'Programaciones de Riego',
                'ordering': ['-prioridad', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_inicio_real', models.TimeField()),
                ('hora_fin_real', models.TimeField(blank=True, null=True)),
                ('duracion_real_minutos', models.IntegerField(blank=True, help_text='Duración real del riego en minutos', null=True)),
                ('caudal_real_litros_minuto', models.DecimalField(blank=True, decimal_places=2, help_text='Caudal real medido', max_digits=10, null=True)),
                ('consumo_total_litros', models.DecimalField(blank=True, decimal_places=2, help_text='Consumo total de agua en litros', max_digits=10, null=True)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('parcial', 'Parcial'), ('cancelado', 'Cancelado')], default='exitoso', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('temperatura_ambiente', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura ambiente en °C', max_digits=5, null=True)),
                ('humedad_suelo_antes', models.DecimalField(blank=True, decimal_places=2, help_text='Humedad del suelo antes del riego (%)', max_digits=5, null=True)),
                ('humedad_suelo_despues', models.DecimalField(blank=True, decimal_places=2, help_text='Humedad del suelo después del riego (%)', max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_riego', to='zonas_riego.zona')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='programaciones.programacion')),
            ],
            options={
                'verbose_name': 'Historial de Riego',
                'verbose_name_plural': 'Historiales de Riego',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
