# Generated by Django 5.2.8 on 2025-11-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialRiego',
        ),
    ]
